spring.application.name=verdictsphere
spring.datasource.url=jdbc:mysql://localhost:3306/firstdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=firstuser
spring.datasource.password=First@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=VerdictSphereSecretKey2024VeryLongSecretForHS256Algorithm
jwt.expiration.ms=900000

# Admin seeds
admin1.email=admin1@verdictsphere.com
admin1.password=Admin@123
admin1.firstName=Admin
admin1.lastName=One

admin2.email=admin2@verdictsphere.com
admin2.password=Admin@123
admin2.firstName=Admin
admin2.lastName=Two

admin3.email=admin3@verdictsphere.com
admin3.password=Admin@123
admin3.firstName=Admin
admin3.lastName=Three
